server:
  port: 8081
  servlet:
    context-path: /pay

pay:
  alipay:
    enable: true
    app-id: ''
    private-key: ''
    public-key: ''
    notify-url: ''
    char-set: ''
    format: ''
    sign-type: ''