server:
  port: 8081
spring:
  mvc:
    static-path-pattern: classpath:/static
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
  level:
    root: info
springdoc:
  swagger-ui:
    path: /pay/swagger-ui.html
pay:
  union:
    enable: true
    merchant-id: 777290058203758
    notify-url: http://123.com
    sign-cert-path: classpath:cert/acp_test_sign.pfx
    sign-cert-pwd: '000000'
    sign-type: '01'