server:
  port: 8081
spring:
  mvc:
    static-path-pattern: classpath:/static

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
  level:
    root: info
springdoc:
  swagger-ui:
    path: /pay/swagger-ui.html

