server:
  port: 8081
spring:
  mvc:
    static-path-pattern: classpath:/static
  rabbitmq:
    host: 10.10.10.10
    port: 5672
    username: root
    password: admin
    virtual-host: /
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
  level:
    root: info
springdoc:
  swagger-ui:
    path: /pay/swagger-ui.html
pay:
  union:
    merchant-id: 777290058203758
    sign-cert-path: classpath:certs/acp_test_sign.pfx
    sign-cert-pwd: '000000'
    sign-type: '01'
    success-notify-url: http://xxx.123.com
    refund-notify-url: http://xxx.213.com
    root-cert-path: classpath:certs/acp_test_root.cer
  paypal:
    client-id: 'AepSvAFACXR9Hn47x0y3k1djxEZcyddsu38-1lljCc46QL7qDPnzumLVHd0jGQP6j4nusHJn-vilViKN'
    secret: 'EOlieRfkze-IeEEbT1tvYsVXUXncs0UYHoXeKIW4fUOrL3Mjmw5a-bpWj7nhHW93f624U6QXnO2YZ9uC'
    notify-url: 'https://baidu.com'
    currency: USD
  jd:
    des-key: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
    merchant-id: 16546165132191165
    public-key-path: classpath:jd/public_key.pem
    private-key-path: classpath:jd/private_key.pem
    success-notify-url: https://baidu.com
    refund-notify-url: https://baidu.com
  mq:
    rabbitmq:
      enable: true